spring:
  application:
    name: POC-Spring-Restful-Service-test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa_test
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
  h2:
    console:
      enabled: true
      path: /h2-console-test
      settings:
        trace: false
        web-allow-others: false
        
        
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
